### ISSUE TITLE
kernel-sign-file cannot do PKCS#7 signature

### ISSUE THREAD

**Issue by bluca** [openSUSE/pesign-obs-integration#2]
Since kernel 4.3 the modules are expected to be signed with a PKCS\#7 signature:

https://github.com/torvalds/linux/commit/bc1c373dd2a5113800360f7152be729c9da996cc

But the kernel-sign-file script doesn't do that, so loading modules signed by it (with lockdown enabled, which enforces signature checks) fails:

```
$ sudo modprobe igb_uio
[  744.134136] Module is not signed with expected PKCS#7 message
```

Are there any plans to update the script to cope with this change?

**Comment by bluca** [comment]
Ah I see this was fixed on OBS https://build.opensuse.org/request/show/530628 but never synced back to the repository.

**Comment by akshata494** [comment]
Hey @bluca ,

I just noticed this issue when I was trying to sign+load an out of tree driver module I compiled for SLES 15. I have my own private key that I enroll on the firmware and then I sign my modules with my key pair. I see that the issue is fixed .However I'm unable to figure out where to get a build with this fix that I can install to sign my modules with a PKCS#7 signature? 

Would you be able to point me to such a build, or let me know how I can get this fix in my current signing setup if at all possible? 

Thanks for your help in advance.
